language: node_js
node_js:
  - 10
dist: trusty
sudo: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
addons:
  chrome: stable
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - google-chrome-stable --headless --disable-gpu
install:
  - yarn install
script:
  - yarn test
notifications:
  slack: hemingwayworkspace:EE6Ff0jXRwp7toHG6n141NuX
after_success:
  - npm run travis-deploy-once "npm run release"
