language: node_js

node_js:
  - '10'

dist: trusty

sudo: false

addons:
  chrome: stable

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - yarn install

script:
  - yarn test
